# Generated by Django 5.0.6 on 2024-06-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='caregory_sb',
            new_name='category_sb',
        ),
    ]
